# Generated by Django 2.1.7 on 2019-03-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20190325_0907'),
        ('frobshop address', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
