# Generated by Django 2.1.7 on 2019-03-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_product_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='video_url',
            field=models.URLField(),
        ),
    ]
